import {
  ShoppingCart, Utensils, Car, Lightbulb, Film, Heart,
  ShoppingBag, DollarSign, HelpCircle, Tag, Home, Briefcase,
  Plane, GraduationCap, Gift, Music, Wifi, Phone, CreditCard,
  TrendingUp, Wallet, PiggyBank, Building2, Zap, Droplets,
  Fuel, Bus, Train, Bike, Ship, Coffee, Pizza, Apple,
  Shirt, Watch, Gem, Scissors, Dumbbell, Stethoscope,
  Pill, Baby, Dog, Cat, TreePine, Flower2, Hammer,
  Wrench, Paintbrush, Camera, Tv, Gamepad2, BookOpen,
  Newspaper, Globe, Map, Compass, Umbrella, Sun, Moon,
  CloudRain, Snowflake, Flame, type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  ShoppingCart,
  Utensils,
  Car,
  Lightbulb,
  Film,
  Heart,
  ShoppingBag,
  DollarSign,
  HelpCircle,
  Tag,
  Home,
  Briefcase,
  Plane,
  GraduationCap,
  Gift,
  Music,
  Wifi,
  Phone,
  CreditCard,
  TrendingUp,
  Wallet,
  PiggyBank,
  Building2,
  Zap,
  Droplets,
  Fuel,
  Bus,
  Train,
  Bike,
  Ship,
  Coffee,
  Pizza,
  Apple,
  Shirt,
  Watch,
  Gem,
  Scissors,
  Dumbbell,
  Stethoscope,
  Pill,
  Baby,
  Dog,
  Cat,
  TreePine,
  Flower2,
  Hammer,
  Wrench,
  Paintbrush,
  Camera,
  Tv,
  Gamepad2,
  BookOpen,
  Newspaper,
  Globe,
  Map,
  Compass,
  Umbrella,
  Sun,
  Moon,
  CloudRain,
  Snowflake,
  Flame,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? HelpCircle;
}
